#! /usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bake monitoring module."""

# %% IMPORTS
# - python standard libraries
import argparse
import os
import time
import logging
import socket
import random
from pathlib import Path
from datetime import datetime, UTC

# - for the SAES pump communication
import socket
from bitstring import BitArray

# - phidgets management
from Phidget22.Devices.TemperatureSensor import TemperatureSensor
from Phidget22.Devices.VoltageInput import VoltageInput, VoltageRange
from Phidget22.Devices.LCD import LCD, LCDFont
import daemon

# - database management
from influxdb_client_3 import InfluxDBClient3, Point

import yaml

# %% GLOBAL VARIABLES
BAKERY_ROOT = Path(os.path.dirname(__file__))
CONFIGS_PATH = BAKERY_ROOT / "configs"
CONFIG_FILE_PATH = CONFIGS_PATH / "config.yml"
CONFIG = {}
DATABASE = None
TEMP_SENSORS = []
PRESSURE_GAUGES = []
START_TIME = time.time()
LCD_STRINGS = []
LCD_MODEL_TEMP = "{name:<5}:{value:.1f}{unit}"
LCD_MODEL_PRESSURE = "{name:<5}:{value:.1e}{unit}"
LCD_HANDLER = LCD()

# %% SAES PAYLOAD DICT
SAES_PAYLOAD_DICT = {
    "SERIAL_NUMBER": [48, 80],
    "IOUT": [80, 112],  # nA
    # "VOUT": [112, 128],  # V
    # "VIN": [128, 144],  # dV
    # "TEMPERATURE": [160, 176],  # Kelvin
    # "ARCING_NUMBER": [176, 192],
    # "LIFE_TIME": [192, 224],  # total working hours
    # "UPTIME": [224, 256],  # second elapsed till last start (pump uptime)
    # "STATUS": [256, 272],
    # "SW_STATUS": [272, 280],
    "CONV_RATE": [1048, 1064],  # A/Torr
    # "ONTIME": [288, 320],  # controller uptime (ms)
}
MILLIBAR_PER_TORR = 101325 / 760 / 100

# %% SRS PTC10 GLOBAL SETTINGS
PTC10_COMMAND_LIST = ["*IDN?", "getOutput", "getOutput.names", "getOutput.units"]
PTC10_TEMP_OUTPUTS = {"AOSense Oven": "Oven TC", "AOSense Hot Window": "HW TC"}

# %% LOGGER
# setup format
fmt = "[%(asctime)s] - %(name)s - %(levelname)s - %(message)s"
# config : default level set to Warning
logging.basicConfig(format=fmt, datefmt="%Y-%m-%d %H:%M:%S", level=logging.WARNING)
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logger.debug("debug mode enabled")

# %% GAUGE API (FIXME: to move outside at some point)

# voltage to pressure conversion functions


def _Pfeiffer_IKR270(U):
    """
    Compact Cold Cathode Gauge IKR270
    input  : U = voltage (in Volts)
    output : P = pressuer (in mbar)
    """
    d = 12.75
    P = 10 ** (1.25 * U - d)
    return P


def _Pfeiffer_PKR251(U):
    """
    Compact FullRange Gauge
    input  : U = voltage (in Volts)
    output : P = pressuer (in mbar)
    """
    d = 11.33
    P = 10 ** (1.667 * U - d)
    return P


def _Gamma_Vac_SPC(U, offset=12):
    """
    Gamma Vacuum SPC ion pump controler
    When monitoring set to "logarithmic pressure"
    Offset value depends on selected range (on SPC)
    input  : U = voltage (in Volts)
    output : P = pressuer (in mbar)
    """
    P = 10 ** (U - offset)
    return P


GAUGE_MODELS = {
    "IKR270": _Pfeiffer_IKR270,
    "PKR251": _Pfeiffer_PKR251,
    "GammaSPC": _Gamma_Vac_SPC,
}

# %% FUNCTIONS


def load_config():
    global CONFIG_FILE_PATH, CONFIG
    # logger
    logger = logging.getLogger(__name__)
    logger.debug(f"loading config file {CONFIG_FILE_PATH}")
    # load config
    with CONFIG_FILE_PATH.open() as file:
        CONFIG = yaml.safe_load(file)


def setup_influx_client():
    """Create the connetion to the database."""
    global CONFIG, DATABASE
    # logger
    logger = logging.getLogger(__name__)
    logger.debug(f"setting up influxdb client")
    # setup influx client
    dbconf = CONFIG["influxdb"]
    DATABASE = InfluxDBClient3(
        host=f'http://{dbconf["host"]}:{dbconf["port"]}',
        database=dbconf["database"],
        token=dbconf["token"],
    )


def setup_temperature_sensors():
    global CONFIG, TEMP_SENSORS
    # - get logger
    logger = logging.getLogger(__name__)
    # - loop on temperature sensors
    for conf in CONFIG["temperature sensors"]:
        try:
            # initial checkup
            if not conf["enabled"]:
                continue
            # emulated ?
            conf["emulated"] = False if "emulated" not in conf else conf["emulated"]
            conf["em_str"] = "**emulated**" if conf["emulated"] else ""
            # logger
            logger.debug(
                "add {em_str} temperature sensor > port : {port} | chan : {channel} | loc : {location}".format(
                    **conf
                )
            )
            # init
            ts = TemperatureSensor()
            ts.setHubPort(conf["port"])
            ts.setChannel(conf["channel"])
            ts.tags = {"location": conf["location"], "data_unit": "°C"}
            ts.display_name = conf["display name"]
            ts.display_unit = "C"
            ts.alarm = conf["alarm"]
            ts.min = conf["min"]
            ts.max = conf["max"]
            ts.emulated = conf["emulated"]
            if not ts.emulated:
                ts.openWaitForAttachment(1000)
            else:
                ts.temperature = 20.0  # initial fake temperature for "realistic" fake data
            # append to list
            TEMP_SENSORS.append(ts)
        except Exception as e:
            logger.error(e)


def setup_pressure_gauges():
    global CONFIG, PRESSURE_GAUGES, GAUGE_MODELS
    # - get logger
    logger = logging.getLogger(__name__)
    # - loop on temperature sensors
    for conf in CONFIG["pressure gauges"]:
        try:
            # initial checkup
            if not conf["enabled"]:
                continue
            # logger
            logger.debug(
                "add pressure gauge > port : {port} | model : {model} | loc : {location}".format(
                    **conf
                )
            )
            # check that model is implemented
            if conf["model"] not in GAUGE_MODELS.keys():
                logger.error("gauge model {model} is not implemented".format(**conf))
                continue
            # init
            pg = VoltageInput()
            pg.setHubPort(conf["port"])
            pg.tags = {"location": conf["location"], "data_unit": "mbar"}
            pg.display_name = conf["display name"]
            pg.display_unit = "mbar"
            pg.conversion_function = GAUGE_MODELS[conf["model"]]
            pg.alarm = conf["alarm"]
            pg.min = conf["min"]
            pg.max = conf["max"]
            pg.openWaitForAttachment(1000)
            pg.setVoltageRange(VoltageRange.VOLTAGE_RANGE_40V)
            # append to list
            PRESSURE_GAUGES.append(pg)
        except Exception as e:
            logger.error(e)


def setup_LCD():
    global CONFIG, LCD_HANDLER
    if CONFIG["global"]["lcd"]:
        LCD_HANDLER.openWaitForAttachment(1000)
        LCD_HANDLER.setBacklight(0.2)


def _write_point(fields, extra_tags=dict(), current_time=None):
    global CONFIG, DATABASE
    # get info from config
    global_tags = CONFIG["global"]["tags"]
    measurement = CONFIG["global"]["measurement"]
    # prepare tags
    tags = {}
    tags.update(global_tags)
    tags.update(extra_tags)
    # get current time
    if current_time is None:
        current_time = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    # prepare point
    point = Point.from_dict(
        {
            "measurement": measurement,
            "tags": tags,
            "time": current_time,
            "fields": fields,
        }
    )
    # write to DB
    DATABASE.write(point)


def _measure():
    global TEMP_SENSORS, PRESSURE_GAUGES, LCD_STRINGS, LCD_MODEL_TEMP, LCD_MODEL_PRESSURE, CONFIG, MILLIBAR_PER_TORR, PTC10_TEMP_OUTPUTS
    # get logger
    logger = logging.getLogger(__name__)
    # current time
    current_time = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    LCD_STRINGS = []
    # temperature
    for ts in TEMP_SENSORS:
        new_temperature = -1
        try:
            if ts.emulated:
                # for an emulated sensor, we have a random fluctation
                dT = (random.random() - 0.5) / 3.
                ts.temperature += dT
                new_temperature = ts.temperature
            else:
                # otherwise, we measure temperature
                new_temperature = ts.getTemperature()
            _write_point(
                fields={"temperature": new_temperature},
                extra_tags=ts.tags,
                current_time=current_time,
            )
        except Exception as e:
            logger.error(e)
        if CONFIG["global"]["lcd"]:
            str = LCD_MODEL_TEMP.format(
                name=ts.display_name, value=new_temperature, unit=ts.display_unit
            )
            if ts.alarm and (new_temperature < ts.min or new_temperature > ts.max):
                if int(2 * time.time()) % 2:  # blinking
                    str += "!"
                else:
                    str += " "
            else:
                str += " "
            LCD_STRINGS.append(str)

    # pressure gauges
    # we start a new line on the LCD
    if len(LCD_STRINGS) % 2:
        LCD_STRINGS.append("")
    LCD_STRINGS.append("-" * 100)
    LCD_STRINGS.append("")

    # get pressure values
    for pg in PRESSURE_GAUGES:
        new_voltage = -1
        try:
            new_voltage = pg.getVoltage()
            new_pressure = pg.conversion_function(new_voltage)
            _write_point(
                fields={"voltage": new_voltage, "pressure": new_pressure},
                extra_tags=pg.tags,
                current_time=current_time,
            )
        except Exception as e:
            logger.error(e)
        if CONFIG["global"]["lcd"]:
            str = LCD_MODEL_PRESSURE.format(
                name=pg.display_name, value=new_pressure, unit=pg.display_unit
            )
            if pg.alarm and (new_pressure < pg.min or new_pressure > pg.max):
                if int(2 * time.time()) % 2:  # blinking
                    str += "!"
                else:
                    str += " "
            else:
                str += " "
            LCD_STRINGS.append(str)
            LCD_STRINGS.append("")
    # SAES
    if CONFIG["global"].get("SAES_enabled"):
        result = _get_SAES_data()
        if result:
            new_current = result["IOUT"]
            new_pressure = new_current * 1e-9 / result["CONV_RATE"] * MILLIBAR_PER_TORR
            tags = {"location": "SAES ion pump", "data_unit": "mbar"}
            _write_point(
                fields={"current": new_current, "pressure": new_pressure},
                extra_tags=tags,
                current_time=current_time,
            )
            if CONFIG["global"]["lcd"]:
                str = LCD_MODEL_PRESSURE.format(
                    name="SAES", value=new_pressure, unit="mbar"
                )
                LCD_STRINGS.append(str)
                LCD_STRINGS.append("")

    # PTC10
    if CONFIG["global"].get("PTC10_enabled"):
        result = _get_PTC10_data()
        if result:
            outputs = result["outputs"]
            device = result["device"]
            for location, output_name in PTC10_TEMP_OUTPUTS.items():
                if output_name in outputs:
                    new_temperature = outputs[output_name]["value"]
                    tags = {
                        "location": location,
                        "data_unit": "°C",
                        "device": "PTC10",
                        "device_serial_number": device["S/N"],
                    }
                    _write_point(
                        fields={"temperature": new_temperature},
                        extra_tags=tags,
                        current_time=current_time,
                    )


def _update_LCD():
    global CONFIG, LCD_STRINGS, LCD_HANDLER
    if not CONFIG["global"]["lcd"]:
        return
    line = 0
    line_height = 8
    line_width = 65
    font = LCDFont.FONT_5x8
    for str in LCD_STRINGS:
        x = (line % 2) * line_width
        y = (line // 2) * line_height
        LCD_HANDLER.writeText(font, x, y, str)
        line += 1
    LCD_HANDLER.flush()


# --- SAES PUMP


def _get_SAES_data():
    global CONFIG, SAES_PAYLOAD_DICT
    result = False
    try:
        # - get configuration
        ip = CONFIG["global"]["SAES_IP"]
        port = CONFIG["global"]["SAES_port"]
        # - prepare socket and send payload
        payload = bytes.fromhex("0105")
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.sendto(payload, (ip, port))
        s.settimeout(0.1)
        # - get result
        data, address = s.recvfrom(302)
        payload = data[2:]  # /!\ BYTES
        payload_bits = BitArray(bytes=payload)
        # - parse result
        # we'll store all the "raw" results in this dict
        result = {}
        for key, bitrange in SAES_PAYLOAD_DICT.items():
            value = payload_bits[bitrange[0] : bitrange[1]]
            if key in [
                "STATUS",
            ]:
                result[key] = value
            else:
                result[key] = value.int

    except Exception as e:
        logger.error(e)
    finally:
        return result


# --- PTC10 temperature controler


def _get_PTC10_data():
    global PTC10_COMMAND_LIST
    result = False
    try:
        # - get configuration
        ip = CONFIG["global"]["PTC10_IP"]
        port = CONFIG["global"]["PTC10_port"]
        # - prepare ascii message and convert to byte
        ascii_msg = "\n".join(PTC10_COMMAND_LIST) + "\n"
        raw_msg = bytes(ascii_msg, "ascii")
        # - open socket
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(1.0)
        s.connect((ip, port))
        s.sendall(raw_msg)
        # - get reply
        reply = {}
        for cmd in PTC10_COMMAND_LIST:
            data = s.recv(4096)
            reply[cmd] = data
        # close socket
        s.close()
        # - parse result
        # convert reply to string
        for msg, raw_str in reply.items():
            good_str = raw_str.decode("latin-1")  # no shit...
            good_str = good_str.replace("\r", "")
            good_str = good_str.replace("\n", "")
            reply[msg] = good_str.split(",")
        # get outputs
        outputs = {}
        for val, name, unit in zip(
            reply["getOutput"], reply["getOutput.names"], reply["getOutput.units"]
        ):
            # remove leading & trailing spaces
            val = val.strip()
            name = name.strip()
            unit = unit.strip()
            # store
            outputs[name] = {"value": float(val), "unit": unit}
        # get device info
        provider, device, SN, firmware = reply["*IDN?"]
        device = {"provider": provider, "name": device, "S/N": SN, "firmware": firmware}
        result = {"outputs": outputs, "device": device}
    except Exception as e:
        logger.error(e)
    finally:
        return result


# --- Monitoring


def start_monitoring():
    global START_TIME, CONFIG
    # get logger
    logger = logging.getLogger(__name__)
    logger.debug("----------- START MONITORING -------------")
    # get config
    max_duration = CONFIG["global"]["max_duration"]
    data_interval = CONFIG["global"]["data_interval"]
    last_measurement = time.time()
    while True:
        # check if finished
        if max_duration and time.time() - START_TIME > max_duration:
            duration = time.time() - START_TIME
            logger.debug(f"measurement stopped after {duration} seconds")
            break
        # new measurement ?
        if time.time() - last_measurement > data_interval:
            last_measurement = time.time()
            t0 = time.time()
            _measure()
            _update_LCD()
            t1 = time.time()
            logger.debug(f"measurement done in {t1-t0}s")
        time.sleep(data_interval / 20)


def display_IP():
    global CONFIG, LCD_STRINGS, LCD_HANDLER
    # - get logger
    logger = logging.getLogger(__name__)
    # - get IP
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        # doesn't even have to be reachable
        s.connect(("10.255.255.255", 1))
        ip_address = s.getsockname()[0]
    except Exception:
        ip_address = "127.0.0.1"
    finally:
        s.close()
    # - get hostname
    hostname = socket.gethostname()
    logger.debug(f"IP : {ip_address} | hostname : {hostname}")
    # - display on LCD
    if CONFIG["global"]["lcd"]:
        font = LCDFont.FONT_5x8
        msg = f"{ip_address}"
        LCD_HANDLER.writeText(font, 0, 64 - 8, msg)


# %% MAIN
def main():
    load_config()
    setup_LCD()
    display_IP()
    setup_influx_client()
    setup_temperature_sensors()
    setup_pressure_gauges()
    start_monitoring()


# %% RUN
if __name__ == "__main__":
    # -- get arguments
    # configure parser
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--config", type=str, help="config file name")
    parser.add_argument(
        "-d", "--deamon", action="store_true", help="Start pasqwatch as a deamon"
    )

    # process config argument
    args = parser.parse_args()
    conf_name = args.config
    if conf_name is not None:
        CONFIG_FILE_PATH = CONFIGS_PATH / conf_name

    # -- start
    if args.deamon is True:
        with daemon.DaemonContext():
            main()
    else:
        main()
