#! /usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bake monitoring module."""

# %% IMPORTS
# - python standard libraries
import argparse
import os
import time
import logging
import socket
from pathlib import Path
from datetime import datetime

# - phidgets management
from Phidget22.Devices.TemperatureSensor import TemperatureSensor
from Phidget22.Devices.VoltageInput import VoltageInput, VoltageRange
from Phidget22.Devices.LCD import LCD, LCDFont
import daemon

# - database management
from influxdb_client import InfluxDBClient, Point
from influxdb_client.client.write_api import SYNCHRONOUS

import yaml

# %% GLOBAL VARIABLES
PASQWATCH_ROOT = Path(os.path.dirname(__file__))
CONFIGS_PATH = PASQWATCH_ROOT / "configs"
CONFIG_FILE_PATH = CONFIGS_PATH / "config.yml"
CONFIG = {}
DATABASE = None
TEMP_SENSORS = []
PRESSURE_GAUGES = []
START_TIME = time.time()
LCD_STRINGS = []
LCD_MODEL_TEMP = "{name:<5}:{value:.1f}{unit}"
LCD_MODEL_PRESSURE = "{name:<5}:{value:.1e}{unit}"
LCD_HANDLER = LCD()

# %% LOGGER
# setup format
fmt = "[%(asctime)s] - %(name)s - %(levelname)s - %(message)s"
# config : default level set to Warning
logging.basicConfig(format=fmt, datefmt="%Y-%m-%d %H:%M:%S", level=logging.WARNING)
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logger.debug("debug mode enabled")

# %% GAUGE API (FIXME: to move outside at some point)

# voltage to pressure conversion functions


def _Pfeiffer_IKR270(U):
    """
    Compact Cold Cathode Gauge IKR270
    input  : U = voltage (in Volts)
    output : P = pressuer (in mbar)
    """
    d = 12.75
    P = 10 ** (1.25 * U - d)
    return P


def _Pfeiffer_PKR251(U):
    """
    Compact FullRange Gauge
    input  : U = voltage (in Volts)
    output : P = pressuer (in mbar)
    """
    d = 11.33
    P = 10 ** (1.667 * U - d)
    return P


GAUGE_MODELS = {"IKR270": _Pfeiffer_IKR270, "PKR251": _Pfeiffer_PKR251}

# %% FUNCTIONS


def load_config():
    global CONFIG_FILE_PATH, CONFIG
    # logger
    logger = logging.getLogger(__name__)
    logger.debug(f"loading config file {CONFIG_FILE_PATH}")
    # load config
    with CONFIG_FILE_PATH.open() as file:
        CONFIG = yaml.safe_load(file)


def setup_influx_client():
    """Create the connetion to the database."""
    global CONFIG, DATABASE
    # logger
    logger = logging.getLogger(__name__)
    logger.debug(f"setting up influxdb client")
    # setup influx client
    dbconf = CONFIG["influxdb"]
    DATABASE = InfluxDBClient(
        url=f'http://{dbconf["host"]}:{dbconf["port"]}',
        org=dbconf["org"],
        token=dbconf["token"],
    )


def setup_temperature_sensors():
    global CONFIG, TEMP_SENSORS
    # - get logger
    logger = logging.getLogger(__name__)
    # - loop on temperature sensors
    for conf in CONFIG["temperature sensors"]:
        try:
            # initial checkup
            if not conf["enabled"]:
                continue
            # logger
            logger.debug(
                "add temperature sensor > port : {port} | chan : {channel} | loc : {location}".format(
                    **conf
                )
            )
            # init
            ts = TemperatureSensor()
            ts.setHubPort(conf["port"])
            ts.setChannel(conf["channel"])
            ts.tags = {"location": conf["location"], "data_unit": "°C"}
            ts.display_name = conf["display name"]
            ts.display_unit = "C"
            ts.alarm = conf["alarm"]
            ts.min = conf["min"]
            ts.max = conf["max"]
            ts.openWaitForAttachment(1000)
            # append to list
            TEMP_SENSORS.append(ts)
        except Exception as e:
            logger.error(e)


def setup_pressure_gauges():
    global CONFIG, PRESSURE_GAUGES, GAUGE_MODELS
    # - get logger
    logger = logging.getLogger(__name__)
    # - loop on temperature sensors
    for conf in CONFIG["pressure gauges"]:
        try:
            # initial checkup
            if not conf["enabled"]:
                continue
            # logger
            logger.debug(
                "add pressure gauge > port : {port} | model : {model} | loc : {location}".format(
                    **conf
                )
            )
            # check that model is implemented
            if conf["model"] not in GAUGE_MODELS.keys():
                logger.error("gauge model {model} is not implemented".format(**conf))
                continue
            # init
            pg = VoltageInput()
            pg.setHubPort(conf["port"])
            pg.tags = {"location": conf["location"], "data_unit": "mbar"}
            pg.display_name = conf["display name"]
            pg.display_unit = "mbar"
            pg.conversion_function = GAUGE_MODELS[conf["model"]]
            pg.alarm = conf["alarm"]
            pg.min = conf["min"]
            pg.max = conf["max"]
            pg.openWaitForAttachment(1000)
            pg.setVoltageRange(VoltageRange.VOLTAGE_RANGE_40V)
            # append to list
            PRESSURE_GAUGES.append(pg)
        except Exception as e:
            logger.error(e)


def setup_LCD():
    global CONFIG, LCD_HANDLER
    if CONFIG["global"]["lcd"]:
        LCD_HANDLER.openWaitForAttachment(1000)
        LCD_HANDLER.setBacklight(0.2)


def _write_point(fields, extra_tags=dict(), current_time=None):
    global CONFIG, DATABASE
    # get info from config
    bucket = CONFIG["global"]["bucket"]
    global_tags = CONFIG["global"]["tags"]
    measurement = CONFIG["global"]["measurement"]
    # prepare tags
    tags = {}
    tags.update(global_tags)
    tags.update(extra_tags)
    # get current time
    if current_time is None:
        current_time = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    # prepare point
    point = Point.from_dict(
        {
            "measurement": measurement,
            "tags": tags,
            "time": current_time,
            "fields": fields,
        }
    )
    # write to DB
    write_api = DATABASE.write_api(write_options=SYNCHRONOUS)
    write_api.write(bucket, DATABASE.org, point)


def _measure():
    global TEMP_SENSORS, PRESSURE_GAUGES, LCD_STRINGS, LCD_MODEL_TEMP, LCD_MODEL_PRESSURE, CONFIG
    # get logger
    logger = logging.getLogger(__name__)
    # current time
    current_time = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    LCD_STRINGS = []
    # temperature
    for ts in TEMP_SENSORS:
        new_temperature = -1
        try:
            new_temperature = ts.getTemperature()
            _write_point(
                fields={"temperature": new_temperature},
                extra_tags=ts.tags,
                current_time=current_time,
            )
        except Exception as e:
            logger.error(e)
        if CONFIG["global"]["lcd"]:
            str = LCD_MODEL_TEMP.format(
                name=ts.display_name, value=new_temperature, unit=ts.display_unit
            )
            if ts.alarm and (new_temperature < ts.min or new_temperature > ts.max):
                if int(2 * time.time()) % 2:  # blinking
                    str += "!"
                else:
                    str += " "
            else:
                str += " "
            LCD_STRINGS.append(str)

    # pressure gauges
    # we start a new line on the LCD
    if len(LCD_STRINGS) % 2:
        LCD_STRINGS.append("")
    LCD_STRINGS.append("-" * 100)
    LCD_STRINGS.append("")

    # get pressure values
    for pg in PRESSURE_GAUGES:
        new_voltage = -1
        try:
            new_voltage = pg.getVoltage()
            new_pressure = pg.conversion_function(new_voltage)
            _write_point(
                fields={"voltage": new_voltage, "pressure":new_pressure},
                extra_tags=pg.tags,
                current_time=current_time,
            )
        except Exception as e:
            logger.error(e)
        if CONFIG["global"]["lcd"]:
            str = LCD_MODEL_PRESSURE.format(
                name=pg.display_name, value=new_pressure, unit=pg.display_unit
            )
            if pg.alarm and (new_temperature < pg.min or new_temperature > pg.max):
                if int(2 * time.time()) % 2:  # blinking
                    str += "!"
                else:
                    str += " "
            else:
                str += " "
            LCD_STRINGS.append(str)
            LCD_STRINGS.append("")


def _update_LCD():
    global CONFIG, LCD_STRINGS, LCD_HANDLER
    if not CONFIG["global"]["lcd"]:
        return
    line = 0
    line_height = 8
    line_width = 65
    font = LCDFont.FONT_5x8
    for str in LCD_STRINGS:
        x = (line % 2) * line_width
        y = (line // 2) * line_height
        LCD_HANDLER.writeText(font, x, y, str)
        line += 1
    LCD_HANDLER.flush()


def start_monitoring():
    global START_TIME, CONFIG
    # get logger
    logger = logging.getLogger(__name__)
    logger.debug("----------- START MONITORING -------------")
    # get config
    max_duration = CONFIG["global"]["max_duration"]
    data_interval = CONFIG["global"]["data_interval"]
    last_measurement = time.time()
    while True:
        # check if finished
        if max_duration and time.time() - START_TIME > max_duration:
            duration = time.time() - START_TIME
            logger.debug(f"measurement stopped after {duration} seconds")
            break
        # new measurement ?
        if time.time() - last_measurement > data_interval:
            last_measurement = time.time()
            t0 = time.time()
            _measure()
            _update_LCD()
            t1 = time.time()
            logger.debug(f"measurement done in {t1-t0}s")
        time.sleep(data_interval / 20)


def display_IP():
    global CONFIG, LCD_STRINGS, LCD_HANDLER
    # - get logger
    logger = logging.getLogger(__name__)
    # - get IP
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        # doesn't even have to be reachable
        s.connect(("10.255.255.255", 1))
        ip_address = s.getsockname()[0]
    except Exception:
        ip_address = "127.0.0.1"
    finally:
        s.close()
    # - get hostname
    hostname = socket.gethostname()
    logger.debug(f"IP : {ip_address} | hostname : {hostname}")
    # - display on LCD
    if CONFIG["global"]["lcd"]:
        font = LCDFont.FONT_5x8
        msg = f"{ip_address}"
        LCD_HANDLER.writeText(font, 0, 64 - 8, msg)


# %% MAIN
def main():
    load_config()
    setup_LCD()
    display_IP()
    setup_influx_client()
    setup_temperature_sensors()
    setup_pressure_gauges()
    start_monitoring()


# %% RUN
if __name__ == "__main__":
    # -- get arguments
    # configure parser
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--config", type=str, help="config file name")
    parser.add_argument(
        "-d", "--deamon", action="store_true", help="Start pasqwatch as a deamon"
    )

    # process config argument
    args = parser.parse_args()
    conf_name = args.config
    if conf_name is not None:
        CONFIG_FILE_PATH = CONFIGS_PATH / conf_name

    # -- start
    if args.deamon is True:
        with daemon.DaemonContext():
            main()
    else:
        main()
