#! /usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bake monitoring module."""

# %% IMPORTS
# - python standard libraries
import argparse
import os
import time
import logging
from logging.handlers import RotatingFileHandler
import socket
import random
import shutil
from pathlib import Path
from datetime import datetime, UTC

# - for the SAES pump communication
import socket
from bitstring import BitArray

# - phidgets management
from Phidget22.Devices.TemperatureSensor import TemperatureSensor
from Phidget22.Devices.VoltageInput import VoltageInput, VoltageRange
from Phidget22.Devices.LCD import LCD, LCDFont
import daemon

# - database management
import requests
import sqlite3
import json

# - for configuration management
import yaml

# %% GLOBAL VARIABLES
BAKERY_ROOT = Path(os.path.dirname(__file__))
CONFIG_EXAMPLE_PATH = BAKERY_ROOT / "config_example.yml"
CONF_FOLDER = Path.home() / ".bakery"
CONFIG_FILE_PATH = CONF_FOLDER / "config.yml"
LOG_FILE_PATH = CONF_FOLDER / "bakery.log"
BUFFER_DATABASE_PATH = CONF_FOLDER / "buffer_database.sqlite"
BUFFER_DATABASE_CONNECTION = None
CONFIG = {}
DATABASE = None
TEMP_SENSORS = []
PRESSURE_GAUGES = []
START_TIME = time.time()
LCD_STRINGS = []
LCD_MODEL_TEMP = "{name:<5}:{value:.1f}{unit}"
LCD_MODEL_PRESSURE = "{name:<5}:{value:.1e}{unit}"
LCD_HANDLER = LCD()
LCD_SPINNER_SEQ = ["-", "\\", "|", "/"]
LCD_SPINNER_STATE = 0

# %% SAES PAYLOAD DICT
SAES_PAYLOAD_DICT = {
    "SERIAL_NUMBER": [48, 80],
    "IOUT": [80, 112],  # nA
    # "VOUT": [112, 128],  # V
    # "VIN": [128, 144],  # dV
    "TEMPERATURE": [160, 176],  # Kelvin
    # "ARCING_NUMBER": [176, 192],
    # "LIFE_TIME": [192, 224],  # total working hours
    # "UPTIME": [224, 256],  # second elapsed till last start (pump uptime)
    "STATUS": [256, 272],
    # "SW_STATUS": [272, 280],
    "CONV_RATE": [1048, 1064],  # A/Torr
    # "ONTIME": [288, 320],  # controller uptime (ms)
}
MILLIBAR_PER_TORR = 101325 / 760 / 100

# %% SRS PTC10 GLOBAL SETTINGS
PTC10_COMMAND_LIST = ["*IDN?", "getOutput", "getOutput.names", "getOutput.units"]
PTC10_TEMP_OUTPUTS = {"AOSense Oven": "Oven TC", "AOSense Hot Window": "HW TC"}

# %% LOGGER
# setup format
fmt = "[%(asctime)s] - %(name)s - %(levelname)s - %(message)s"
# config : default level set to INFO
logging.basicConfig(format=fmt, datefmt="%Y-%m-%d %H:%M:%S", level=logging.INFO)
logger = logging.getLogger(__name__)


# %% INFLUXDB HTTP CLIENT
"""Homemade client, in order to avoid the use of the influxdb3 python 
library for compatibility reasons"""


class InfluxHTTPClient(object):
    """a simple client for putting data to influxDB3 database using the http api v3"""

    API_URL = "/api/v3/write_lp"
    HOST_URL = "http://{host}:{port}"

    def __init__(self, host, port, token, database):
        self.host = host
        self.port = port
        self.token = token
        self.database = database
        self._line_fmt = "{table},{tags} {fields} {timestamp:02d}\n"

    def _escape_str(self, str):
        characters = [" ", ",", "="]
        for c in characters:
            str = str.replace(c, "\\" + c)
        return str

    def _write_line(self, table, tag_dict, field_dict, timestamp_ms=None):
        # prepare timestamp
        if timestamp_ms is None:
            timestamp_seconds = int(datetime.now(UTC).timestamp())
            timestamp_ms = timestamp_seconds * 1000
        timestamp_ms = int(timestamp_ms)
        # prepare tags
        tags = ",".join(
            [
                f"{self._escape_str(k)}={self._escape_str(v)}"
                for k, v in tag_dict.items()
            ]
        )
        # prepare fields
        fields = ",".join([f"{self._escape_str(k)}={v}" for k, v in field_dict.items()])
        # write line
        data_dict = {
            "tags": tags,
            "fields": fields,
            "table": table,
            "timestamp": timestamp_ms,
        }
        line = self._line_fmt.format(**data_dict)
        return line

    def _post_data(self, raw_data):
        # prepare request
        req_url = self.HOST_URL.format(host=self.host, port=self.port) + self.API_URL
        params = {"db": self.database, "precision": "millisecond"}
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "text/plain; charset=utf-8",
        }
        data = raw_data.encode("utf8")
        # post
        return requests.post(
            req_url, headers=headers, params=params, data=data, timeout=2
        )

    def write_data(self, points):
        """writes data to the database.
        points shoud be a dict or a list of dict, with keys :
         'table' : a string indicating the table
         'tags' : a dict with tags keys and values
         'fields' : a dict with fields keys and values
         'timestamp' : a unix timestamp in ms, or None (get current timestamp)
        """
        # init data
        data = ""
        # handle unique point
        if isinstance(points, dict):
            points = [
                points,
            ]
        # prepare data
        for p in points:
            data += self._write_line(
                table=p["table"],
                tag_dict=p["tags"],
                field_dict=p["fields"],
                timestamp_ms=p["timestamp"],
            )
        # write
        res = self._post_data(data)

        if res.status_code != 204:
            raise Exception(res.text)


# %% GAUGE API (FIXME: to move outside at some point)

# voltage to pressure conversion functions


def _Pfeiffer_IKR270(U):
    """
    Compact Cold Cathode Gauge IKR270
    input  : U = voltage (in Volts)
    output : P = pressuer (in mbar)
    """
    d = 12.75
    P = 10 ** (1.25 * U - d)
    return P


def _Pfeiffer_PKR251(U):
    """
    Compact FullRange Gauge
    input  : U = voltage (in Volts)
    output : P = pressuer (in mbar)
    """
    d = 11.33
    P = 10 ** (1.667 * U - d)
    return P


def _Gamma_Vac_SPC(U, offset=12):
    """
    Gamma Vacuum SPC ion pump controler
    When monitoring set to "logarithmic pressure"
    Offset value depends on selected range (on SPC)
    input  : U = voltage (in Volts)
    output : P = pressuer (in mbar)
    """
    P = 10 ** (U - offset)
    return P


GAUGE_MODELS = {
    "IKR270": _Pfeiffer_IKR270,
    "PKR251": _Pfeiffer_PKR251,
    "GammaSPC": _Gamma_Vac_SPC,
}

# %% FUNCTIONS


def check_folders():
    global CONFIG_FILE_PATH, CONF_FOLDER, CONFIG_EXAMPLE_PATH
    # logger
    logger = logging.getLogger(__name__)
    logger.debug(f"checking folders")
    # check that the config folder exists; create if not
    logger.debug(f"create config folder {CONF_FOLDER} if not done yet")
    CONF_FOLDER.mkdir(exist_ok=True)
    # check if the config file exists, otherwise copy example
    if not CONFIG_FILE_PATH.is_file():
        logger.warning(f"configuration file not found >> copying example config")
        logger.warning(
            f"change the configuration file according to your needs : {CONFIG_FILE_PATH}"
        )
        shutil.copy(CONFIG_EXAMPLE_PATH, CONFIG_FILE_PATH)


def load_config():
    global CONFIG_FILE_PATH, CONFIG
    # logger
    logger = logging.getLogger(__name__)
    logger.debug(f"loading config file {CONFIG_FILE_PATH}")
    # load config
    with CONFIG_FILE_PATH.open() as file:
        CONFIG = yaml.safe_load(file)


def setup_influx_client():
    """Create the connetion to the database."""
    global CONFIG, DATABASE
    # logger
    logger = logging.getLogger(__name__)
    logger.debug(f"setting up influxdb client")
    # setup influx client
    dbconf = CONFIG["influxdb"]
    DATABASE = InfluxHTTPClient(
        host=dbconf["host"],
        port=dbconf["port"],
        database=dbconf["database"],
        token=dbconf["token"],
    )


def setup_buffer_database():
    global BUFFER_DATABASE_PATH, BUFFER_DATABASE_CONNECTION, CONFIG
    # connect / create database
    connection = sqlite3.connect(BUFFER_DATABASE_PATH)
    # create table
    cursor = connection.cursor()
    table = CONFIG["influxdb"]["database"]
    cursor.execute(
        f"CREATE TABLE IF NOT EXISTS {table} (id INTEGER PRIMARY KEY AUTOINCREMENT, point_json TEXT)"
    )
    BUFFER_DATABASE_CONNECTION = connection


def setup_temperature_sensors():
    global CONFIG, TEMP_SENSORS
    # - get logger
    logger = logging.getLogger(__name__)
    # - loop on temperature sensors
    for conf in CONFIG["temperature sensors"]:
        try:
            # initial checkup
            if not conf["enabled"]:
                continue
            # emulated ?
            conf["emulated"] = False if "emulated" not in conf else conf["emulated"]
            conf["em_str"] = "**emulated**" if conf["emulated"] else ""
            # logger
            logger.debug(
                "add {em_str} temperature sensor > port : {port} | chan : {channel} | loc : {location}".format(
                    **conf
                )
            )
            # init
            ts = TemperatureSensor()
            ts.setHubPort(conf["port"])
            ts.setChannel(conf["channel"])
            ts.tags = {"location": conf["location"], "data_unit": "°C"}
            ts.display_name = conf["display name"]
            ts.display_unit = "C"
            ts.alarm = conf["alarm"]
            ts.min = conf["min"]
            ts.max = conf["max"]
            ts.emulated = conf["emulated"]
            if not ts.emulated:
                ts.openWaitForAttachment(1000)
            else:
                ts.temperature = (
                    20.0  # initial fake temperature for "realistic" fake data
                )
            # append to list
            TEMP_SENSORS.append(ts)
        except Exception as e:
            logger.error(e)


def setup_pressure_gauges():
    global CONFIG, PRESSURE_GAUGES, GAUGE_MODELS
    # - get logger
    logger = logging.getLogger(__name__)
    # - loop on temperature sensors
    for conf in CONFIG["pressure gauges"]:
        try:
            # initial checkup
            if not conf["enabled"]:
                continue
            # logger
            logger.debug(
                "add pressure gauge > port : {port} | model : {model} | loc : {location}".format(
                    **conf
                )
            )
            # check that model is implemented
            if conf["model"] not in GAUGE_MODELS.keys():
                logger.error("gauge model {model} is not implemented".format(**conf))
                continue
            # init
            pg = VoltageInput()
            pg.setHubPort(conf["port"])
            pg.tags = {"location": conf["location"], "data_unit": "mbar"}
            pg.display_name = conf["display name"]
            pg.display_unit = "mbar"
            pg.conversion_function = GAUGE_MODELS[conf["model"]]
            pg.alarm = conf["alarm"]
            pg.min = conf["min"]
            pg.max = conf["max"]
            pg.openWaitForAttachment(1000)
            pg.setVoltageRange(VoltageRange.VOLTAGE_RANGE_40V)
            # append to list
            PRESSURE_GAUGES.append(pg)
        except Exception as e:
            logger.error(e)


def setup_LCD():
    global CONFIG, LCD_HANDLER
    if CONFIG["global"]["lcd"]:
        LCD_HANDLER.openWaitForAttachment(1000)
        LCD_HANDLER.setBacklight(0.2)


def _write_point(fields, extra_tags=dict(), current_time=None):
    global CONFIG, DATABASE
    # get logger
    logger = logging.getLogger(__name__)
    # get info from config
    global_tags = CONFIG["global"]["tags"]
    measurement = CONFIG["global"]["measurement"]
    # prepare tags
    tags = {}
    tags.update(global_tags)
    tags.update(extra_tags)
    # get current time
    if current_time is None:
        current_time = int(datetime.now(UTC).timestamp() * 1000)  # in ms
    # prepare point
    point_dict = {
        "table": measurement,
        "tags": tags,
        "timestamp": current_time,
        "fields": fields,
    }

    # write to DB
    write_success = False
    try:
        DATABASE.write_data(point_dict)
        write_success = True
    except Exception as e:
        logger.error(e)

    # in case of error, save in buffer database
    if not write_success:
        logger.debug("error writing in database > storing in local buffer database")
        # convert to json string for easy storage
        point_json_str = json.dumps(point_dict)
        # cursor for sqlite
        cursor = BUFFER_DATABASE_CONNECTION.cursor()
        table = CONFIG["influxdb"]["database"]
        data = (point_json_str,)
        cursor.execute(f"INSERT INTO {table} (point_json) VALUES (?)", data)
        BUFFER_DATABASE_CONNECTION.commit()


def _measure():
    global TEMP_SENSORS, PRESSURE_GAUGES, LCD_STRINGS, LCD_MODEL_TEMP, LCD_MODEL_PRESSURE, CONFIG, MILLIBAR_PER_TORR, PTC10_TEMP_OUTPUTS
    # get logger
    logger = logging.getLogger(__name__)
    # current time
    current_time = int(datetime.now(UTC).timestamp() * 1000)  # in ms
    LCD_STRINGS = []
    # temperature
    for ts in TEMP_SENSORS:
        new_temperature = -1
        try:
            if ts.emulated:
                # for an emulated sensor, we have a random fluctation
                dT = (random.random() - 0.5) / 3.0
                ts.temperature += dT
                new_temperature = ts.temperature
            else:
                # otherwise, we measure temperature
                new_temperature = ts.getTemperature()
            _write_point(
                fields={"temperature": new_temperature},
                extra_tags=ts.tags,
                current_time=current_time,
            )
        except Exception as e:
            logger.error(e)
        if CONFIG["global"]["lcd"]:
            str = LCD_MODEL_TEMP.format(
                name=ts.display_name, value=new_temperature, unit=ts.display_unit
            )
            if ts.alarm and (new_temperature < ts.min or new_temperature > ts.max):
                if int(2 * time.time()) % 2:  # blinking
                    str += "!"
                else:
                    str += " "
            else:
                str += " "
            LCD_STRINGS.append(str)

    # pressure gauges
    # we start a new line on the LCD
    if len(LCD_STRINGS) % 2:
        LCD_STRINGS.append("")
    LCD_STRINGS.append("-" * 100)
    LCD_STRINGS.append("")

    # get pressure values
    for pg in PRESSURE_GAUGES:
        new_voltage = -1
        try:
            new_voltage = pg.getVoltage()
            new_pressure = pg.conversion_function(new_voltage)
            _write_point(
                fields={"voltage": new_voltage, "pressure": new_pressure},
                extra_tags=pg.tags,
                current_time=current_time,
            )
        except Exception as e:
            logger.error(e)
        if CONFIG["global"]["lcd"]:
            str = LCD_MODEL_PRESSURE.format(
                name=pg.display_name, value=new_pressure, unit=pg.display_unit
            )
            if pg.alarm and (new_pressure < pg.min or new_pressure > pg.max):
                if int(2 * time.time()) % 2:  # blinking
                    str += "!"
                else:
                    str += " "
            else:
                str += " "
            LCD_STRINGS.append(str)
            LCD_STRINGS.append("")
    # SAES
    if CONFIG["global"].get("SAES_enabled"):
        result = _get_SAES_data()
        if result:
            new_current = result["IOUT"]
            new_pressure = new_current * 1e-9 / result["CONV_RATE"] * MILLIBAR_PER_TORR
            temperature_K = result["TEMPERATURE"]
            temperature_degC = temperature_K - 273.15
            tags = {"location": "SAES ion pump", "data_unit": "mbar"}
            _write_point(
                fields={
                    "current": new_current,
                    "pressure": new_pressure,
                    "temperature": temperature_degC,
                },
                extra_tags=tags,
                current_time=current_time,
            )
            if CONFIG["global"]["lcd"]:
                str = LCD_MODEL_PRESSURE.format(
                    name="SAES", value=new_pressure, unit="mbar"
                )
                LCD_STRINGS.append(str)
                LCD_STRINGS.append("")

    # PTC10
    if CONFIG["global"].get("PTC10_enabled"):
        result = _get_PTC10_data()
        if result:
            outputs = result["outputs"]
            device = result["device"]
            for location, output_name in PTC10_TEMP_OUTPUTS.items():
                if output_name in outputs:
                    new_temperature = outputs[output_name]["value"]
                    tags = {
                        "location": location,
                        "data_unit": "°C",
                        "device": "PTC10",
                        "device_serial_number": device["S/N"],
                    }
                    _write_point(
                        fields={"temperature": new_temperature},
                        extra_tags=tags,
                        current_time=current_time,
                    )


def _update_LCD():
    global CONFIG, LCD_STRINGS, LCD_HANDLER, LCD_SPINNER_SEQ, LCD_SPINNER_STATE
    if not CONFIG["global"]["lcd"]:
        return
    # Write data
    line = 0
    line_height = 8
    line_width = 65
    font = LCDFont.FONT_5x8
    for str in LCD_STRINGS:
        x = (line % 2) * line_width
        y = (line // 2) * line_height
        LCD_HANDLER.writeText(font, x, y, str)
        line += 1

    # Update spinner
    spinner_str = LCD_SPINNER_SEQ[LCD_SPINNER_STATE % len(LCD_SPINNER_SEQ)]
    LCD_SPINNER_STATE += 1
    # screen size is 128 x 64, and one character is 5 x 8
    # so position of down right corner is 128-5, 64-8
    LCD_HANDLER.writeText(font, 128 - 5, 64 - 8, spinner_str)

    # Flush
    LCD_HANDLER.flush()


# --- CRUMBS PICKER


def send_locally_stored_data_to_influx():
    global CONFIG, DATABASE, BUFFER_DATABASE_CONNECTION
    """This function checks if data is stored in the local sqlite
    database - due to an error when trying to write to the influxdb database,
    and tries to upload this data to the influxdb database again. In case of success,
    data is removed from the local database."""
    # - get logger
    logger = logging.getLogger(__name__)
    # - get data from the local database
    logger.debug("get data from the local database")
    cursor = BUFFER_DATABASE_CONNECTION.cursor()
    table = CONFIG["influxdb"]["database"]
    res = cursor.execute(f"SELECT * from {table}")
    data = res.fetchall()
    n_points = len(data)
    logger.debug(f"found {n_points} points to collect !")
    # - convert to points
    n_success = 0
    id_uploaded = []
    sql_args = []
    point_list = []
    for d in data:
        id, point_json = d
        try:
            point_dict = json.loads(point_json)
            point_list.append(point_dict)
            id_uploaded.append(id)
            sql_args.append("?")
        except Exception as e:
            logger.error(f"Exception caught converting point id={id} : {e}")
    # - upload to influx
    logger.debug("upload to influxdb database")
    if point_list:
        try:
            DATABASE.write_data(point_list)
        except Exception as e:
            logger.error(e)
            return

    # - remove uploaded
    n_success = len(id_uploaded)
    logger.debug(f"uploaded {n_success} points to influxdatabase !")
    if n_success:
        arg_str = ", ".join(sql_args)
        cursor.execute(f"DELETE from {table} where id IN ({arg_str})", id_uploaded)
        BUFFER_DATABASE_CONNECTION.commit()
    logger.debug(f"point removed from local database")


# --- SAES PUMP


def _get_SAES_data():
    global CONFIG, SAES_PAYLOAD_DICT
    result = False
    try:
        # - get configuration
        ip = CONFIG["global"]["SAES_IP"]
        port = CONFIG["global"]["SAES_port"]
        # - prepare socket and send payload
        payload = bytes.fromhex("0105")
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.sendto(payload, (ip, port))
        s.settimeout(0.1)
        # - get result
        data, address = s.recvfrom(302)
        payload = data[2:]  # /!\ BYTES
        payload_bits = BitArray(bytes=payload)
        # - parse result
        # we'll store all the "raw" results in this dict
        result = {}
        for key, bitrange in SAES_PAYLOAD_DICT.items():
            value = payload_bits[bitrange[0] : bitrange[1]]
            if key in [
                "STATUS",
            ]:
                result[key] = value
            else:
                result[key] = value.int

    except Exception as e:
        logger.error(e)
    finally:
        return result


# --- PTC10 temperature controler


def _get_PTC10_data():
    global PTC10_COMMAND_LIST
    result = False
    try:
        # - get configuration
        ip = CONFIG["global"]["PTC10_IP"]
        port = CONFIG["global"]["PTC10_port"]
        # - prepare ascii message and convert to byte
        ascii_msg = "\n".join(PTC10_COMMAND_LIST) + "\n"
        raw_msg = bytes(ascii_msg, "ascii")
        # - open socket
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(1.0)
        s.connect((ip, port))
        s.sendall(raw_msg)
        # - get reply
        reply = {}
        for cmd in PTC10_COMMAND_LIST:
            data = s.recv(4096)
            reply[cmd] = data
        # close socket
        s.close()
        # - parse result
        # convert reply to string
        for msg, raw_str in reply.items():
            good_str = raw_str.decode("latin-1")  # no shit...
            good_str = good_str.replace("\r", "")
            good_str = good_str.replace("\n", "")
            reply[msg] = good_str.split(",")
        # get outputs
        outputs = {}
        for val, name, unit in zip(
            reply["getOutput"], reply["getOutput.names"], reply["getOutput.units"]
        ):
            # remove leading & trailing spaces
            val = val.strip()
            name = name.strip()
            unit = unit.strip()
            # store
            outputs[name] = {"value": float(val), "unit": unit}
        # get device info
        provider, device, SN, firmware = reply["*IDN?"]
        device = {"provider": provider, "name": device, "S/N": SN, "firmware": firmware}
        result = {"outputs": outputs, "device": device}
    except Exception as e:
        logger.error(e)
    finally:
        return result


# --- Monitoring


def start_monitoring():
    global START_TIME, CONFIG
    # get logger
    logger = logging.getLogger(__name__)
    logger.debug("----------- START MONITORING -------------")
    # get config
    max_duration = CONFIG["global"]["max_duration"]
    data_interval = CONFIG["global"]["data_interval"]
    last_measurement = time.time()
    while True:
        # check if finished
        if max_duration and time.time() - START_TIME > max_duration:
            duration = time.time() - START_TIME
            logger.debug(f"measurement stopped after {duration} seconds")
            break
        # new measurement ?
        if time.time() - last_measurement > data_interval:
            last_measurement = time.time()
            t0 = time.time()
            _measure()
            _update_LCD()
            t1 = time.time()
            logger.debug(f"measurement done in {t1-t0}s")
        time.sleep(data_interval / 20)


def display_IP():
    global CONFIG, LCD_STRINGS, LCD_HANDLER
    # - get logger
    logger = logging.getLogger(__name__)
    # - get IP
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        # doesn't even have to be reachable
        s.connect(("10.255.255.255", 1))
        ip_address = s.getsockname()[0]
    except Exception:
        ip_address = "127.0.0.1"
    finally:
        s.close()
    # - get hostname
    hostname = socket.gethostname()
    logger.debug(f"IP : {ip_address} | hostname : {hostname}")
    # - display on LCD
    if CONFIG["global"]["lcd"]:
        font = LCDFont.FONT_5x8
        msg = f"{ip_address}"
        LCD_HANDLER.writeText(font, 0, 64 - 8, msg)


# %% MAIN
def main():
    check_folders()
    load_config()
    setup_buffer_database()
    setup_LCD()
    display_IP()
    setup_influx_client()
    setup_temperature_sensors()
    setup_pressure_gauges()
    start_monitoring()


def pick_crumbs():
    check_folders()
    load_config()
    setup_buffer_database()
    setup_influx_client()
    send_locally_stored_data_to_influx()


# %% RUN
if __name__ == "__main__":
    # -- get arguments
    # configure parser
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--config", type=str, help="config file path")
    parser.add_argument(
        "-d", "--deamon", action="store_true", help="Start bakery as a deamon"
    )
    parser.add_argument("--debug", action="store_true", help="Start in debug mode")
    parser.add_argument(
        "--log2file", action="store_true", help="Stores the logs in a file"
    )
    parser.add_argument(
        "--pick-crumbs",
        action="store_true",
        help="Collects locally stored data and tries to upload it to the database. Only runs once.",
    )

    # process config argument
    args = parser.parse_args()
    conf_path = args.config
    if conf_path is not None:
        CONFIG_FILE_PATH = conf_path

    # -- handle logger
    if args.debug:
        logger.setLevel(logging.DEBUG)
        logger.debug("debug mode enabled")

    if args.log2file:
        logger.info(f"logging to {LOG_FILE_PATH}")
        handler = RotatingFileHandler(
            LOG_FILE_PATH,  # Log file name
            maxBytes=100000,  # Maximum size of a log file in bytes before rotation
            backupCount=3,  # Number of backup files to keep
        )
        formatter = logging.Formatter(
            "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        )
        handler.setFormatter(formatter)
        logger.addHandler(handler)

    # -- collect crumbs ?
    if args.pick_crumbs:
        logger.info("starting crumbs picker")
        pick_crumbs()
        exit()

    # -- start
    if args.deamon is True:
        with daemon.DaemonContext():
            logger.info("starting bakery (daemon mode)")
            main()
    else:
        logger.info("starting bakery")
        main()
