# influxDB configuration
influxdb:
  host: 10.105.118.238
  port: 8181
  token: "put token here"
  database: sandbox 

# global configuration attributes
global:
  measurement: bake
  tags:
    room: room name
    site: site name
  max_duration: 0 # s (0 = infinity loop)
  data_interval: 0.5 # s
  lcd: false
  SAES_IP: 127.0.0.1 #10.1.0.10
  SAES_port: 2527
  SAES_enabled: false

# list of temperature sensors
# (phidgets)
temperature sensors:
  # emulated sensor (for tests)
  - port: 0
    channel: 0
    location: dummy sensor
    display name: DMY
    alarm: false
    max: 0
    min: 500
    enabled: true
    emulated: true

  # IP
  - port: 0
    channel: 0
    location: ion pump
    display name: IP
    alarm: false
    max: 0
    min: 500
    enabled: false


# list of pressure gauges
# (phidgets)
pressure gauges:
  # IP
  - port: 2
    location: pumping station
    model: PKR251
    display name: TMP
    alarm: false
    max: 1
    min: 0
    enabled: false
