# influxDB configuration
influxdb:
  host: 192.168.1.1
  port: 8086
  org: "ORG"
  token: "puttokenhere"

# global configuration attributes
global:
  bucket: sandbox  # will be "Altair" then
  measurement: bake
  tags:
    room: room name
    site: site name
  max_duration: 0 # s (0 = infinity loop)
  data_interval: 0.5 # s
  lcd: false
  SAES_IP: 127.0.0.1 #10.1.0.10
  SAES_port: 2527
  SAES_enabled: true

# list of temperature sensors
# (phidgets)
temperature sensors:
  # IP
  - port: 0
    channel: 0
    location: ion pump
    display name: IP
    alarm: false
    max: 0
    min: 500
    enabled: false


# list of pressure gauges
# (phidgets)
pressure gauges:
  # IP
  - port: 2
    location: pumping station
    model: PKR251
    display name: TMP
    alarm: false
    max: 1
    min: 0
    enabled: false
